authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
   path('login/', views.login, name='login'),
   path('logout/', views.logout, name='logout'),
   path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
   path('password_reset/', views.password_reset, name='password_reset'),
   path('sign_up/', views.sign_up, name='sign_up'),
   path('delete_account/', views.delete_account, name='delete_account'),
   path('update_account/', views.update_account, name='update_account'),
]

resume/urls.py
from django.contrib import admin
from django.urls import path, include

from resume import views

from .api.views import *

app_name = 'resume'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('profile/update_user', views.update_user, name='update_user'),
    
    path('experience', views.experience, name='experience'),
    path('experience/create_experience', views.create_experience, name='create_experience'),
    path('experience/update_experience', views.update_experience, name='update_experience'),
    path('experience/delete_experience/<int:id>', views.delete_experience, name='delete_experience'),

    path('education', views.education, name='education'),
    path('education/create_education', views.create_education, name='create_education'),
    path('education/update_education', views.update_education, name='update_education'),
    path('education/delete_education/<int:id>', views.delete_education, name='delete_education'),

    path('skills', views.skills, name='skills'),
    path('skills/create_skill', views.create_skill, name='create_skill'),
    path('skills/delete_skill/<int:id>', views.delete_skill, name='delete_skill'),

    path('settings', views.settings, name='settings'),
    path('settings/set_green', views.set_green, name='set_green'),
    path('settings/set_pink', views.set_pink, name='set_pink'),
    path('settings/set_blue', views.set_blue, name='set_blue'),
    path('settings/set_orange', views.set_orange, name='set_orange'),

    path('generate_resume', views.generate_resume, name='generate_resume'),

    path('api/v1/experience/', ExperienceList.as_view()),
    path('api/v1/experience/<int:pk>/', ExperienceDetail.as_view()),
    path('api/v1/education/', EducationList.as_view()),
    path('api/v1/education/<int:pk>/', EducationDetail.as_view()),
]

resume_builder/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers, serializers, viewsets
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume.urls')),
    path('authentication/', include('authentication.urls')),
    path('rest/', include('rest_auth.urls')),
    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}'

authentication/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from . models import PasswordResetRequest
from . messaging import email_message
import django_rq


def login(request):
    context = {}

    if request.method == "POST":
        user = authenticate(
            request, username=request.POST['user'], password=request.POST['password'])
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('resume:profile'))
        else:
            context = {
                'error': 'Bad username or password.'
            }
    return render(request, 'authentication/login.html', context)


def logout(request):
    dj_logout(request)
    return render(request, 'authentication/login.html')


def request_password_reset(request):
    if request.method == "POST":
        post_user = request.POST['username']
        user = None

        if post_user:
            try:
                user = User.objects.get(username=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        else:
            post_user = request.POST['email']
            try:
                user = User.objects.get(email=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        if user:
            prr = PasswordResetRequest()
            prr.user = user
            prr.save()
            django_rq.enqueue(email_message, {
               'token' : prr.token,
               'email' : prr.user.email,
            })
            return HttpResponseRedirect(reverse('authentication:password_reset'))

    return render(request, 'authentication/request_password_reset.html')


def password_reset(request):
    if request.method == "POST":
        post_user = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        token = request.POST['token']

        if password == confirm_password:
            try:
                prr = PasswordResetRequest.objects.get(token=token)
                prr.save()
            except:
                print("Invalid password reset attempt.")
                return render(request, 'authentication/password_reset.html')

            user = prr.user
            user.set_password(password)
            user.save()
            return HttpResponseRedirect(reverse('authentication:login'))

    return render(request, 'authentication/password_reset.html')


def sign_up(request):
    context = {}
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user_name = request.POST['user']
        email = request.POST['email']
        if password == confirm_password:
            if User.objects.create_user(user_name, email, password):
                return HttpResponseRedirect(reverse('authentication:login'))
            else:
                context = {
                    'error': 'Could not create user account - please try again.'
                }
        else:
            context = {
                'error': 'Passwords did not match. Please try again.'
            }
    return render(request, 'authentication/sign_up.html', context)

@login_required
def delete_account(request):
    if request.method == "POST":
        if request.POST['confirm_deletion'] == "DELETE":
            user = authenticate(
                request, username=request.user.username, password=request.POST['password'])
            if user:
                print(f"Deleting user {user}")
                user.delete()
                return HttpResponseRedirect(reverse('authentication:login'))
            else:
                print("fail delete")

    return render(request, 'authentication/delete_account.html')


@login_required
def update_account(request):
    request.user.first_name = request.POST['firstName']
    request.user.last_name = request.POST['lastName']
    request.user.email = request.POST['email']
    print(request.user.first_name)
    request.user.save()
    return HttpResponseRedirect(reverse('resume:profile'))

authentication/templates/authentication/base.html
{% load static %}

<!doctype html>
<html lang="en" data-theme="green">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Resume-builder</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
	<link href="{% static 'resume/css/style.css' %}" rel="stylesheet">
	<script src="../static/pagination.js"></script>
</head>

<body>
	<main role="main">
		<div class="container">
			<div class="content">
					{% block content %}
					{% endblock %}	  
			</div>
		  </div>
		  
	</main>

</body>

</html>

authentication/templates/authentication/delete_account.html
{% extends "authentication/base.html" %}

{% block content %}
<div id="delete" class="auth">
	<form action="{% url 'authentication:delete_account' %}" method="POST" class="form-signin">
		{% csrf_token %}
		<h1 class="h3 mb-3 font-weight-normal"> Confirm Account Deletetion </h1>
		<input type="password" name="password" class="form-control" placeholder="Password" required>
		<input type="text" name="confirm_deletion" class="form-control" placeholder="Type DELETE" required>
		<button class="btn btn-lg btn-primary btn-block">Delete</button>
		{% if error %}
		<h6 class="error">{{ error }}</h6>
		{% endif %}
	</form>
</div>
{% endblock %}

authentication/templates/authentication/login.html
{% extends "authentication/base.html" %}

{% block content %}
<div id="login" class="auth">
	<form action="{% url 'authentication:login' %}" method="POST">
		{% csrf_token %}
		<h1>Log in |<a href="{% url 'authentication:sign_up' %}"> Sign Up</a></h1>
		<input type="text" name="user" placeholder="Username" required autofocus>
		<input type="password" name="password" placeholder="Password" required>
		<button type="submit">Log in</button>
		<a href="{% url 'authentication:request_password_reset' %}">Forgotten Password?</a>
		{% if error %}
		<h6>{{ error }}</h6>
		{% endif %}
	</form>
</div>
{% endblock %}

authentication/templates/authentication/password_reset.html
{% extends "authentication/base.html" %}

{% block content %}
<div id="reset" class="auth">
	<form action="{% url 'authentication:password_reset' %}" method="POST" class="form-signin">
		{% csrf_token %}
		<input type="text" name="username" class="form-control" placeholder="User Name" required autofocus>
		<input type="password" name="password" class="form-control" placeholder="New Password" required>
		<input type="password" name="confirm_password" class="form-control" placeholder="Repeat New Password" required>
		<input type="text" name="token" class="form-control" placeholder="Token" required>
		<button class="btn btn-lg btn-primary btn-block">Submit</button>
		{% if error %}
		<h6 class="error">{{ error }}</h6>
		{% endif %}
	</form>
</div>
{% endblock %}

authentication/templates/authentication/request_password_reset.html
{% extends "authentication/base.html" %}

{% block content %}
<div id="request-reset" class="auth">
	<form action="{% url 'authentication:request_password_reset' %}" method="POST" class="form-signin">
		{% csrf_token %}
		<h1 class="h3 mb-3 font-weight-normal"> Insert your Username and Email</h1>
		<input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
		<input type="email" name="email" class="form-control" placeholder="Email" required>
		<button class="btn btn-lg btn-primary btn-block">Submit</button>
		{% if error %}
		<h6 class="error">{{ error }}</h6>
		{% endif %}
	</form>
</div>
{% endblock %}

authentication/templates/authentication/sign_up.html
{% extends "authentication/base.html" %}

{% block content %}
<div id="signup" class="auth">
	<form action="{% url 'authentication:sign_up' %}" method="POST" class="form-signin">
		{% csrf_token %}
		<h1 class="h3 mb-3 font-weight-normal"><a href="{% url 'authentication:login' %}"> Log in </a>| Sign Up</h1>
		<input type="text" name="user" class="form-control" placeholder="Username" required autofocus>
		<input type="email" name="email" class="form-control" placeholder="Email" required autofocus>
		<input type="password" name="password" class="form-control" placeholder="Password" required>
		<input type="password" name="confirm_password" class="form-control" placeholder="Repete Password" required>
		<button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
		{% if error %}
		<h6 class="error">{{ error }}</h6>
		{% endif %}
	</form>
</div>
{% endblock %}