authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
   path('login/', views.login, name='login'),
   path('logout/', views.logout, name='logout'),
   path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
   path('password_reset/', views.password_reset, name='password_reset'),
   path('sign_up/', views.sign_up, name='sign_up'),
   path('delete_account/', views.delete_account, name='delete_account'),
   path('update_account/', views.update_account, name='update_account'),
]

resume/urls.py
from django.contrib import admin
from django.urls import path, include

from resume import views

from .api.views import *

app_name = 'resume'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('profile/update_user', views.update_user, name='update_user'),
    
    path('experience', views.experience, name='experience'),
    path('experience/create_experience', views.create_experience, name='create_experience'),
    path('experience/update_experience', views.update_experience, name='update_experience'),
    path('experience/delete_experience/<int:id>', views.delete_experience, name='delete_experience'),

    path('education', views.education, name='education'),
    path('education/create_education', views.create_education, name='create_education'),
    path('education/update_education', views.update_education, name='update_education'),
    path('education/delete_education/<int:id>', views.delete_education, name='delete_education'),

    path('skills', views.skills, name='skills'),
    path('skills/create_skill', views.create_skill, name='create_skill'),
    path('skills/delete_skill/<int:id>', views.delete_skill, name='delete_skill'),

    path('settings', views.settings, name='settings'),
    path('settings/set_green', views.set_green, name='set_green'),
    path('settings/set_pink', views.set_pink, name='set_pink'),
    path('settings/set_blue', views.set_blue, name='set_blue'),
    path('settings/set_orange', views.set_orange, name='set_orange'),

    path('generate_resume', views.generate_resume, name='generate_resume'),

    path('api/v1/experience/', ExperienceList.as_view()),
    path('api/v1/experience/<int:pk>/', ExperienceDetail.as_view()),
    path('api/v1/education/', EducationList.as_view()),
    path('api/v1/education/<int:pk>/', EducationDetail.as_view()),
]

resume_builder/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers, serializers, viewsets
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume.urls')),
    path('authentication/', include('authentication.urls')),
    path('rest/', include('rest_auth.urls')),
    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
]

resume/models.py
from django.db import models
from django.contrib.auth.models import User
from user_profile.models import UserProfile

class Experience(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, default='')
	company = models.CharField(max_length=200)
	role = models.CharField(max_length=200)
	startDate = models.DateField()
	endDate = models.DateField()
	description = models.CharField(max_length=500)

	def __str__(self):
		return self.company

class Education(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, default='')
	school = models.CharField(max_length=200)
	degree = models.CharField(max_length=200)
	startDate = models.DateField()
	endDate = models.DateField()
	description = models.CharField(max_length=500)

	def __str__(self):
		return self.school

class Skill(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, default='')
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name

resume/api/views.py
from rest_framework import generics, permissions
from rest_framework.response import Response
from ..models import Experience, Education
from .serializers import ExperienceSerializer
from .serializers import EducationSerializer


class ExperienceList(generics.ListCreateAPIView):
   serializer_class = ExperienceSerializer
   def get_queryset(self):
      if self.request.user.is_authenticated:
         user = self.request.user
         return Experience.objects.filter(user=user)


class ExperienceDetail(generics.RetrieveUpdateDestroyAPIView):
   queryset = Experience.objects.all()
   serializer_class = ExperienceSerializer


class EducationList(generics.ListCreateAPIView):
   queryset = Education.objects.all()
   serializer_class = EducationSerializer


class EducationDetail(generics.RetrieveUpdateDestroyAPIView):
   queryset = Education.objects.all()
   serializer_class = EducationSerializer

resume/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render,  get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


from .utils import render_to_pdf

from .models import Experience, Education, Skill
from user_profile.models import UserProfile


def home(request):
	return render(request, 'resume/homepage.html')

def profile(request):
	user = request.user
	profile = get_object_or_404(UserProfile, user=user)
	context = {
		'first_name': user.first_name,
		'last_name': user.last_name,
		'email': user.email,
		'phone': profile.phone,
		'profession': profile.profession,
		'bio': profile.bio,
		'theme': profile.color,
	}
	return render(request, 'resume/profile.html', context)

def update_user(request):
	user = request.user
	user.first_name = request.POST['first_name']
	user.last_name = request.POST['last_name']
	user.email = request.POST['email']
	user.save()
	profile = get_object_or_404(UserProfile, user=user)
	profile.phone = request.POST['phone']
	profile.profession = request.POST['profession']
	profile.bio = request.POST['bio']
	profile.save()
	return HttpResponseRedirect(reverse('resume:profile'))

################################# CRUD EXPERIENCE

def experience(request):
	user = request.user
	profile = get_object_or_404(UserProfile, user=user)
	experiences = Experience.objects.filter(user=request.user)
	if experience:
		context = {
			'experiences': experiences,
			'theme': profile.color,
		}
		return render(request, 'resume/experience.html', context)
	context = {
		'theme': profile.color,
	}
	return render(request, 'resume/experience.html', context)

def create_experience(request):
	experience = Experience()
	experience.user = request.user
	experience.company = request.POST['company']
	experience.role = request.POST['role']
	experience.startDate = request.POST['start']
	experience.endDate = request.POST['end']
	experience.description = request.POST['description']
	experience.save()
	return HttpResponseRedirect(reverse('resume:experience'))

def update_experience(request):
	id = request.POST['id']
	experience =get_object_or_404(Experience, id=id)
	experience.company = request.POST['company']
	experience.role = request.POST['role']
	# experience.startDate = request.POST['start']
	# experience.endDate = request.POST['end']
	experience.description = request.POST['description']
	experience.save()
	return HttpResponseRedirect(reverse('resume:experience'))

def delete_experience(request, id):
	experience = get_object_or_404(Experience, id=id)
	experience.delete()
	return HttpResponseRedirect(reverse('resume:experience'))

################################# CRUD EDUCAION 

def education(request):
	user = request.user
	profile = get_object_or_404(UserProfile, user=user)
	educations = Education.objects.filter(user=request.user)
	if educations:
		context = {
			'educations': educations,
			'theme': profile.color,
		}
		return render(request, 'resume/education.html', context)
	context = {
		'theme': profile.color,
	}
	return render(request, 'resume/education.html', context)

def create_education(request):
	education = Education()
	education.user = request.user
	education.school = request.POST['school']
	education.degree = request.POST['degree']
	education.startDate = request.POST['start']
	education.endDate = request.POST['end']
	education.description = request.POST['description']
	education.save()
	return HttpResponseRedirect(reverse('resume:education'))

def update_education(request):
	id = request.POST['id']
	education =get_object_or_404(Education, id=id)
	education.school = request.POST['school']
	education.degree = request.POST['degree']
	# education.startDate = request.POST['start']
	# education.endDate = request.POST['end']
	education.description = request.POST['description']
	education.save()
	return HttpResponseRedirect(reverse('resume:education'))

def delete_education(request, id):
	education = get_object_or_404(Education, id=id)
	education.delete()
	return HttpResponseRedirect(reverse('resume:education'))


################################# CRUD SKILL

def skills(request):
	user = request.user
	profile = get_object_or_404(UserProfile, user=user)
	skills = Skill.objects.filter(user=request.user)
	skills = skills[::-1] ##reversing the list
	context = {
		'skills': skills,
		'theme': profile.color,
	}
	return render(request, 'resume/skills.html', context)

def create_skill(request):
	skill = Skill()
	skill.user = request.user
	skill.name = request.POST['name']
	skill.save()
	return HttpResponseRedirect(reverse('resume:skills'))

def delete_skill(request, id):
	skill = get_object_or_404(Skill, id=id)
	skill.delete()
	return HttpResponseRedirect(reverse('resume:skills'))


################################# SETTINGS

def settings(request):
	user = request.user
	profile = get_object_or_404(UserProfile, user=user)
	context = {
		'username': user.username,
		'email': user.email,
		'theme': profile.color,
	}
	return render(request, 'resume/settings.html', context)

def set_blue(request):
	user = request.user
	profile = get_object_or_404(UserProfile, user=user)
	profile.color = 'blue'
	profile.save()
	return HttpResponseRedirect(reverse('resume:settings'))

def set_green(request):
	user = request.user
	profile = get_object_or_404(UserProfile, user=user)
	profile.color = 'green'
	profile.save()
	return HttpResponseRedirect(reverse('resume:settings'))

def set_orange(request):
	user = request.user
	profile = get_object_or_404(UserProfile, user=user)
	profile.color = 'orange'
	profile.save()
	return HttpResponseRedirect(reverse('resume:settings'))

def set_pink(request):
	user = request.user
	profile = get_object_or_404(UserProfile, user=user)
	profile.color = 'pink'
	profile.save()
	return HttpResponseRedirect(reverse('resume:settings'))


################################# BUILD RESUME

def generate_resume(request, *args, **kwargs):
	profile = get_object_or_404(UserProfile, user=request.user)
	experiences = Experience.objects.filter(user=request.user)
	educations = Education.objects.filter(user=request.user)
	skills = Skill.objects.filter(user=request.user)
	context = {
		'full_name': request.user.first_name + ' '  + request.user.last_name,
		'profession': profile.profession,
		'about_me': profile.bio,
		'experiences': experiences,
		'educations': educations,
		'skills': skills,
		'theme': profile.color,
	}
	pdf = render_to_pdf('pdf/test.html', context)
	if pdf:
		response = HttpResponse(pdf, content_type='application/pdf')
		download = request.GET.get("download")
		if download == 'True':
			response['Content-Disposition'] = 'attachment; filename=test.pdf'
		return response
	return HttpResponse('PDF not found')

resume/templates/resume/base.html
{% load static %}

<!doctype html>
<html lang="en" data-theme="{{theme}}">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Resume-builder</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
	<link href="{% static 'resume/css/style.css' %}" rel="stylesheet">
	<script src="{% static 'resume/js/pagination.js' %}"></script>
</head>

<body>
	<main role="main">
		<div class="container">
			{% comment %} <h1 class="logo">Resumi</h1> {% endcomment %}
			<a target="_blank" rel="noopener noreferrer" href="{% url 'resume:generate_resume' %}">
				<div class="CTA">
					<h3>CREATE RESUME</h3>
				</div>
			</a>
			<nav class="menubar">
				<a id="profile" class="{% if request.path == '/profile' %}active{% endif %}" href="{% url 'resume:profile' %}"><i class="fa fa-user"></i></a>
				<a id="experience" class="{% if request.path == '/experience' %}active{% endif %}" href="{% url 'resume:experience' %}"><i class="fa fa-briefcase"></i></a>
				<a id="education" class="{% if request.path == '/education' %}active{% endif %}" href="{% url 'resume:education' %}"><i class="fa fa-graduation-cap"></i></a>
				<a id="skills" class="{% if request.path == '/skills' %}active{% endif %}" href="{% url 'resume:skills' %}"><i class="fa fa-tasks"></i></a>
				<a id="settings" class="{% if request.path == '/settings' %}active{% endif %}" href="{% url 'resume:settings' %}"><i class="fa fa-cog"></i></a>
			</nav>
			<div class="content">
				{% block content %}
				{% endblock %}	  
			</div>
		  </div>		  
	</main>
</body>

</html>

resume/templates/resume/education.html
{% extends "resume/base.html" %}

{% block content %}
{% load static %}

	<div class="education">
		<h1>Educations</h1>
		<div class="slideshow">
			<div class="slide-wrapper">
				{% for education in educations  %}
				<div class="slide">
		
					<form action="{% url 'resume:update_education' %}" method="POST">
						{% csrf_token %}
						<button class="btn"> Save</button>
						<a class="btn delete" href="education/delete_education/{{education.id}}">
							<i class="fa fa-trash" aria-hidden="true"></i>
						</a>
						<h2>School Name</h2>
						<p>
							<input type="text" name="school" value="{{education.school}}">
						</p>
						<h2>Degree</h2>
						<p>
							<input type="text" name="degree" value="{{education.degree}}">
						</p>
						<h2>Start Date</h2>
						<p>
							<input type="text" name="start" value="{{education.startDate}}">
						</p>
						<h2>End Date</h2>
						<p>
							<input type="text" name="end" value="{{education.endDate}}">
						</p>
						<h2>Description</h2>
						<p>
							<textarea name="description"  maxlength="300">{{education.description}}</textarea>
						</p>
						<input name="id" value="{{education.id}}" hidden>
					</form>
				</div>
				{% endfor  %}
				<div class="slide">
					<form action="{% url 'resume:create_education' %}" method="POST">
						{% csrf_token %}
						<button class="btn">Add to your educations</button>
						<h2>School Name</h2>
						<p>
							<input type="text" name="school" value="">
						</p>
						<h2>Degree</h2>
						<p>
							<input type="text" name="degree" value="">
						</p>
						<h2>Start Date</h2>
						<p>
							<input type="date" name="start" value="">
						</p>
						<h2>End Date</h2>
						<p>
							<input type="date" name="end" value="">
						</p>
						<h2>Description</h2>
						<p>
							<textarea name="description"  maxlength="300"></textarea>
						</p>
					</form>
				</div>
			</div>
		</div>
		<div class="pagination-btns">
		{% for education in educations  %}		
			<button id="{{education.id}}" name="page"
					class="btn {% if educations.0 == education %} active {% endif %}"
					onClick="slide(id)">
			</button>
		{% endfor  %}
		</div>
		<button class="btn" onClick="newForm()">+ New Education</button>
	</div>

{% endblock %}

resume/templates/resume/experience.html
{% extends "resume/base.html" %}

{% block content %}
{% load static %}

	<div class="experience">
		<h1>Job Experiences</h1>
		<div class="slideshow">
			<div class="slide-wrapper">
				{% for experience in experiences  %}
				<div class="slide">

					<form action="{% url 'resume:update_experience' %}" method="POST">
						{% csrf_token %}
						<button class="btn">Save</button> 
						<a class="btn delete" href="experience/delete_experience/{{experience.id}}">
							<i class="fa fa-trash" aria-hidden="true"></i>
						</a>
						<h2>Company Name</h2>
						<p>
							<input type="text" name="company" value="{{experience.company}}">
						</p>
						<h2>Role</h2>
						<p>
							<input type="text" name="role" value="{{experience.role}}">
						</p>
						<h2>Start Date</h2>
						<p>
							<input type="text" name="start" value="{{experience.startDate}}">
						</p>
						<h2>End Date</h2>
						<p>
							<input type="text" name="end" value="{{experience.endDate}}">
						</p>
						<h2>Description</h2>
						<p>
							<textarea name="description"  maxlength="300">{{experience.description}}</textarea>
						</p>
						<input name="id" value="{{experience.id}}" hidden>
					</form>
				</div>
				{% endfor  %}
				<div class="slide">
					<form action="{% url 'resume:create_experience' %}" method="POST">
						{% csrf_token %}
						<button class="btn">Add to your experiences</button>
						<h2>Company Name</h2>
						<p>
							<input type="text" name="company" value="">
						</p>
						<h2>Role</h2>
						<p>
							<input type="text" name="role" value="">
						</p>
						<h2>Start Date</h2>
						<p>
							<input type="date" name="start" value="">
						</p>
						<h2>End Date</h2>
						<p>
							<input type="date" name="end" value="">
						</p>
						<h2>Description</h2>
						<p>
							<textarea name="description"  maxlength="300"></textarea>
						</p>
					</form>
				</div>
			</div>
		</div>
		<div class="pagination-btns">
		{% for experience in experiences  %}		
			<button id="{{experience.id}}" name="page"
					class="btn {% if experiences.0 == experience %} active {% endif %}"
					onClick="slide(id)">
			</button>
		{% endfor  %}
		</div>
		<button class="btn" onClick="newForm()">+ New Experience</button>
	</div>


{% endblock %}

resume/templates/resume/profile.html
{% extends "resume/base.html" %}

{% block content %}
{% load static %}

	<div class="profile">
		<h1>Personal Info</h1>
		<form action="{% url 'resume:update_user' %}" method="POST">
			{% csrf_token %}
			<button class="btn">Save</button>
			<h2>Full Name</h2>
			<p class='two-in-one'>
				<input type="text" name="first_name" value="{{first_name}}">
				<input type="text" name="last_name" value="{{last_name}}">
			</p>
			<h2>Profession</h2>
			<p>
				<input type="text" name="profession" value="{{profession}}">
			</p>
			<h2>Email</h2>
			<p>
				<input type="text" name="email" value="{{email}}">
			</p>
			<h2>Phone</h2>
			<p>
				<input type="text" name="phone" value="{{phone}}">
			</p>
			<h2>Bio</h2>
			<p>
				<textarea name="bio" cols="50" rows="4" maxlength="300">{{bio}}</textarea>
			</p>
		</form>
	</div>

{% endblock %}

resume/templates/resume/settings.html
{% extends "resume/base.html" %}

{% block content %}
{% load static %}

	<div class="settings">
		<h1>Account Settings</h1>
		<h2>Gabriele Mannucci</h2>
		{% comment %} <p style="width: 45%;">
			<a href="{% url 'authentication:logout' %}" class="btn" style="float: none;">Reset Password</a>
		</p> {% endcomment %}
		<ul>
			<li>
				<a href="{% url 'authentication:delete_account' %}"  class="btn" style="float: none;">Delete Account</a>
			</li>
			<li>
				<a href="{% url 'authentication:logout' %}" class="btn" style="float: none;">Log Out</a>
			</li>
		</ul>
		<br>
		<h1>Resume Settings</h2>
		<h2>Change theme</h2>
		<div class="themes">
			<a class="theme green {% if theme == 'green' %}active{% endif %}" href="{% url 'resume:set_green' %}"></a>
			<a class="theme blue {% if theme == 'blue' %}active{% endif %}" href="{% url 'resume:set_blue' %}"></a>
			<a class="theme orange {% if theme == 'orange' %}active{% endif %}" href="{% url 'resume:set_orange' %}"></a>
			<a class="theme pink {% if theme == 'pink' %}active{% endif %}" href="{% url 'resume:set_pink' %}"></a>
		</div>
	</div>

{% endblock %}

resume/templates/resume/skills.html
{% extends "resume/base.html" %}

{% block content %}
{% load static %}

	<div class="skills">
		<h1>Skills</h1>
		<button class="btn" onClick="newSkill()">+ New Skill</button>
		<div class="skill-wrapper">
			<div class="skill-container">
				<form action="{% url 'resume:create_skill' %}" method="POST">
					{% csrf_token %}
					<div class="skill new">
						<input type="text" name="name">
						<input type="submit" style="display: none;">
					</div>
				</form>
					
				{% for skill in skills %}
				<div class="skill"><div class="name">{{skill.name}}</div><a href="skills/delete_skill/{{skill.id}}" class="delete"> DELETE </a></div>
				{% endfor  %}
			</div>
		</div>
	</div>

{% endblock %}